// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfgfeeiwpoxiwzlizqam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZ2ZlZWl3cG94aXd6bGl6cWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTI1MzgsImV4cCI6MjA2NDE4ODUzOH0.QZqXBmzNFJW-nZgN2nRRQtadWzA_RRDoRxeIHk0xeKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);